/**
 * Game Loop — sets up Three.js scene, loads the GLB model,
 * hooks into 8th Wall's pipeline-based frame loop, and handles image tracking.
 *
 * Correct flow:
 * 1. Wait for XR8 to load
 * 2. Fetch image-target JSON (generated by @8thwall/image-target-cli)
 * 3. XR8.XrController.configure({ imageTargetData: [...] })
 * 4. XR8.addCameraPipelineModules([...])
 * 5. XR8.run({ canvas })
 * 6. Listen for reality.imagefound / reality.imageupdated / reality.imagelost
 */

import * as THREE from 'three'
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js'
import { createScreenRenderer } from './screen-patcher'

const IMAGE_TARGET_NAME = 'mural'

export function initGameLoop() {
  const XR8 = (window as any).XR8
  const XRExtras = (window as any).XRExtras

  console.log('[GameLoop] XR8:', !!XR8, 'XRExtras:', !!XRExtras)
  console.log('[GameLoop] XR8.XrController:', !!XR8?.XrController)
  console.log('[GameLoop] XR8.GlTextureRenderer:', !!XR8?.GlTextureRenderer)

  // ── Three.js Setup ──────────────────────────────────────────────
  const scene = new THREE.Scene()
  scene.background = null // transparent — let camera feed show through

  const camera = new THREE.PerspectiveCamera(
    75,
    window.innerWidth / window.innerHeight,
    0.01,
    1000
  )

  const renderer = new THREE.WebGLRenderer({ alpha: true, antialias: true })
  renderer.setPixelRatio(window.devicePixelRatio)
  renderer.setSize(window.innerWidth, window.innerHeight)
  renderer.outputColorSpace = THREE.SRGBColorSpace
  renderer.toneMapping = THREE.ACESFilmicToneMapping
  renderer.toneMappingExposure = 1.0
  document.body.appendChild(renderer.domElement)

  // Style the Three.js canvas on top of camera feed
  renderer.domElement.style.position = 'fixed'
  renderer.domElement.style.top = '0'
  renderer.domElement.style.left = '0'
  renderer.domElement.style.width = '100%'
  renderer.domElement.style.height = '100%'
  renderer.domElement.style.zIndex = '1'
  renderer.domElement.style.pointerEvents = 'none'

  // ── Lighting (ambient + directional for model visibility) ────────
  const ambientLight = new THREE.AmbientLight(0xffffff, 1.0)
  scene.add(ambientLight)

  const dirLight = new THREE.DirectionalLight(0xffffff, 1.0)
  dirLight.position.set(2, 5, 3)
  scene.add(dirLight)

  const backLight = new THREE.DirectionalLight(0xffffff, 0.3)
  backLight.position.set(-2, 3, -3)
  scene.add(backLight)

  console.log('[GameLoop] Lighting: ambient=1.0, directional=1.0, back=0.3')

  // ── Screen Renderer ─────────────────────────────────────────────
  const screen = createScreenRenderer()

  // ── GLB Loading ─────────────────────────────────────────────────
  let trackedContent: THREE.Object3D | null = null
  let glbLoaded = false

  new GLTFLoader().load(
    './assets/ImageTracking.glb',
    (gltf) => {
      console.log('[GameLoop] GLB loaded —', gltf.scene.children.length, 'children')

      gltf.scene.traverse((node) => {
        const mesh = node as THREE.Mesh
        if ((mesh as any).isMesh) {
          console.log('[GameLoop]   Mesh:', node.name, 'visible:', node.visible)
          // Make sure all meshes are visible
          node.visible = true
          if (node.name === 'screen_plane') {
            screen.patchMesh(mesh)
            console.log('[GameLoop]   → screen_plane patched for texture')
          }
        }
      })

      trackedContent = gltf.scene
      trackedContent.visible = false
      scene.add(trackedContent)
      glbLoaded = true
      console.log('[GameLoop] Tracked content added to scene (hidden until image found)')
    },
    (progress) => {
      if (progress.total > 0) {
        const pct = Math.round((progress.loaded / progress.total) * 100)
        console.log(`[GameLoop] GLB loading: ${pct}%`)
      }
    },
    (err) => {
      console.error('[GameLoop] Failed to load GLB:', err)
    }
  )

  // ── Custom Pipeline Module — Three.js Rendering ─────────────────
  const threejsPipelineModule = () => ({
    name: 'brickgame-threejs',
    onRender: () => {
      screen.drawReduxState()
      renderer.render(scene, camera)
    },
    onUpdate: () => {},
  })

  // ── Image Tracking Events ───────────────────────────────────────
  // Engine dispatches reality.imagefound / reality.imageupdated / reality.imagelost on window
  // detail = { name, position: {x,y,z}, rotation: {x,y,z,w}, scale, type, properties }

  window.addEventListener('reality.imagefound', (e: any) => {
    const detail = e.detail || e
    console.log('[GameLoop] ★ reality.imagefound:', JSON.stringify({
      name: detail.name,
      position: detail.position,
      rotation: detail.rotation,
      scale: detail.scale,
    }))

    if (detail.name === IMAGE_TARGET_NAME && trackedContent) {
      trackedContent.visible = true
      if (detail.position) {
        trackedContent.position.set(detail.position.x, detail.position.y, detail.position.z)
      }
      if (detail.rotation) {
        trackedContent.quaternion.set(detail.rotation.x, detail.rotation.y, detail.rotation.z, detail.rotation.w)
      }
      if (detail.scale != null) {
        trackedContent.scale.set(detail.scale, detail.scale, detail.scale)
      }
      console.log('[GameLoop] Mesh VISIBLE at', trackedContent.position.toArray())
    }
  })

  window.addEventListener('reality.imageupdated', (e: any) => {
    const detail = e.detail || e
    if (detail.name === IMAGE_TARGET_NAME && trackedContent) {
      if (detail.position) {
        trackedContent.position.set(detail.position.x, detail.position.y, detail.position.z)
      }
      if (detail.rotation) {
        trackedContent.quaternion.set(detail.rotation.x, detail.rotation.y, detail.rotation.z, detail.rotation.w)
      }
      if (detail.scale != null) {
        trackedContent.scale.set(detail.scale, detail.scale, detail.scale)
      }
    }
  })

  window.addEventListener('reality.imagelost', (e: any) => {
    const detail = e.detail || e
    console.log('[GameLoop] reality.imagelost:', detail.name)
    if (detail.name === IMAGE_TARGET_NAME && trackedContent) {
      trackedContent.visible = false
    }
  })

  // Diagnostic events
  window.addEventListener('reality.imageloading', (e: any) => {
    console.log('[GameLoop] reality.imageloading:', JSON.stringify(e.detail))
  })
  window.addEventListener('reality.imagescanning', (e: any) => {
    console.log('[GameLoop] reality.imagescanning:', JSON.stringify(e.detail?.imageTargets?.map((t: any) => t.name)))
  })
  window.addEventListener('realityready', () => {
    console.log('[GameLoop] realityready event fired')
  })

  // ── 8th Wall Session Setup ──────────────────────────────────────

  const startXR = async () => {
    // 1. Fetch the CLI-generated image target JSON
    let imageTargetJson
    try {
      const resp = await fetch('./image-targets/mural.json')
      if (!resp.ok) throw new Error(`HTTP ${resp.status}`)
      imageTargetJson = await resp.json()
      console.log('[GameLoop] Fetched mural.json:', JSON.stringify({
        name: imageTargetJson.name,
        type: imageTargetJson.type,
        imagePath: imageTargetJson.imagePath,
        properties: imageTargetJson.properties,
      }))
    } catch (err) {
      console.error('[GameLoop] Failed to fetch mural.json:', err)
      return
    }

    // 2. Build the image target data for the engine
    // The engine's ImageTargetData type requires: imagePath, name, type, properties,
    //   moveable, physicalWidthInMeters
    const imageTargetData = {
      ...imageTargetJson,
      // Override imagePath if needed (use luminance image for best tracking)
      imagePath: imageTargetJson.imagePath,
      // Engine-required fields not in CLI output:
      moveable: false,
      physicalWidthInMeters: 0.21, // original mural width in meters
    }

    console.log('[GameLoop] Configuring imageTargetData:',
      JSON.stringify({ name: imageTargetData.name, imagePath: imageTargetData.imagePath, type: imageTargetData.type }))

    // 3. Configure image targets BEFORE adding pipeline modules
    XR8.XrController.configure({
      imageTargetData: [imageTargetData],
    })
    console.log('[GameLoop] XR8.XrController.configure() called')

    // 4. Register pipeline modules in the correct order
    //    GlTextureRenderer MUST be first (draws camera feed)
    const pipelineModules = [
      XR8.GlTextureRenderer.pipelineModule(),
      XR8.XrController.pipelineModule(),
      threejsPipelineModule(),
    ]

    // Add XRExtras modules if available
    if (XRExtras?.FullWindowCanvas?.pipelineModule) {
      pipelineModules.push(XRExtras.FullWindowCanvas.pipelineModule())
    }
    if (XRExtras?.Loading?.pipelineModule) {
      pipelineModules.push(XRExtras.Loading.pipelineModule())
    }
    if (XRExtras?.RuntimeError?.pipelineModule) {
      pipelineModules.push(XRExtras.RuntimeError.pipelineModule())
    }

    XR8.addCameraPipelineModules(pipelineModules)
    console.log('[GameLoop] Pipeline modules registered:',
      pipelineModules.map((m: any) => m.name || 'unnamed'))

    // 5. Start the XR8 session
    console.log('[GameLoop] Calling XR8.run()')
    XR8.run({
      canvas: document.getElementById('camerafeed'),
      allowedDevices: XR8.XrConfig.device().ANY,
    })

    // Hide splash
    const splash = document.getElementById('ar-splash')
    if (splash) splash.style.display = 'none'
    console.log('[GameLoop] XR8 session started')
  }

  // ── Splash Screen → Start Session ───────────────────────────────
  const splash = document.getElementById('ar-splash')

  const handleStart = () => {
    console.log('[GameLoop] User tapped splash — starting XR')
    startXR()
  }

  if (splash) {
    splash.addEventListener('click', handleStart)
    splash.addEventListener('touchstart', handleStart)
  } else {
    startXR()
  }

  // ── Window Resize ───────────────────────────────────────────────
  window.addEventListener('resize', () => {
    camera.aspect = window.innerWidth / window.innerHeight
    camera.updateProjectionMatrix()
    renderer.setSize(window.innerWidth, window.innerHeight)
  })
}
