/**
 * Game Loop — sets up Three.js scene, loads the GLB model,
 * hooks into 8th Wall's pipeline-based frame loop, and handles image tracking.
 *
 * Architecture (Two-Canvas Method):
 *   Canvas 1: #camerafeed — owned by 8th Wall / GlTextureRenderer (camera feed)
 *   Canvas 2: #threejs-overlay — transparent Three.js canvas, layered on top
 *
 * Correct flow:
 * 1. Wait for XR8 to load
 * 2. Fetch image-target JSON (generated by @8thwall/image-target-cli)
 * 3. XR8.XrController.configure({ imageTargetData: [...] })
 * 4. XR8.addCameraPipelineModules([...])
 * 5. XR8.run({ canvas })
 * 6. Handle reality.imagefound / reality.imageupdated / reality.imagelost
 *    via pipeline module LISTENERS (not window events!)
 */

import * as THREE from 'three'
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js'
import { createScreenRenderer } from './screen-patcher'

const IMAGE_TARGET_NAME = 'mural'

export function initGameLoop() {
  const XR8 = (window as any).XR8
  const XRExtras = (window as any).XRExtras

  console.log('[GameLoop] XR8:', !!XR8, 'XRExtras:', !!XRExtras)
  console.log('[GameLoop] XR8.XrController:', !!XR8?.XrController)
  console.log('[GameLoop] XR8.GlTextureRenderer:', !!XR8?.GlTextureRenderer)

  // ── Three.js Setup (separate overlay canvas) ────────────────────
  const scene = new THREE.Scene()
  scene.background = null // transparent — let camera feed show through

  const camera = new THREE.PerspectiveCamera(
    75,
    window.innerWidth / window.innerHeight,
    0.01,
    1000
  )

  const renderer = new THREE.WebGLRenderer({ alpha: true, antialias: true })
  renderer.setPixelRatio(window.devicePixelRatio)
  renderer.setSize(window.innerWidth, window.innerHeight)
  renderer.outputColorSpace = THREE.SRGBColorSpace
  renderer.toneMapping = THREE.ACESFilmicToneMapping
  renderer.toneMappingExposure = 1.0
  renderer.setClearColor(0x000000, 0) // fully transparent clear

  // Style the Three.js canvas on top of camera feed
  const threeCanvas = renderer.domElement
  threeCanvas.id = 'threejs-overlay'
  threeCanvas.style.position = 'fixed'
  threeCanvas.style.top = '0'
  threeCanvas.style.left = '0'
  threeCanvas.style.width = '100%'
  threeCanvas.style.height = '100%'
  threeCanvas.style.zIndex = '1'
  threeCanvas.style.pointerEvents = 'none'
  document.body.appendChild(threeCanvas)

  // ── Lighting (ambient + directional for model visibility) ────────
  const ambientLight = new THREE.AmbientLight(0xffffff, 1.0)
  scene.add(ambientLight)

  const dirLight = new THREE.DirectionalLight(0xffffff, 1.0)
  dirLight.position.set(2, 5, 3)
  scene.add(dirLight)

  const backLight = new THREE.DirectionalLight(0xffffff, 0.3)
  backLight.position.set(-2, 3, -3)
  scene.add(backLight)

  console.log('[GameLoop] Lighting: ambient=1.0, directional=1.0, back=0.3')

  // ── Screen Renderer ─────────────────────────────────────────────
  const screen = createScreenRenderer()

  // ── GLB Loading ─────────────────────────────────────────────────
  // We wrap the loaded model in a targetGroup so we can apply
  // manual calibration offsets (position, rotation, scale) to the model
  // independently of the 8th Wall SLAM pose updates applied to the group.
  const targetGroup = new THREE.Group()
  targetGroup.visible = false
  scene.add(targetGroup)
  let glbLoaded = false

  new GLTFLoader().load(
    './assets/ImageTracking.glb',
    (gltf) => {
      console.log('[GameLoop] GLB loaded —', gltf.scene.children.length, 'children')

      gltf.scene.traverse((node) => {
        const mesh = node as THREE.Mesh
        if ((mesh as any).isMesh) {
          node.visible = true
          if (node.name === 'screen_plane') {
            screen.patchMesh(mesh)
          }
        }
      })

      const modelMesh = gltf.scene
      targetGroup.add(modelMesh)
      glbLoaded = true
      console.log('[GameLoop] Tracked content added to targetGroup')

      // Create Calibration UI to adjust modelMesh inside targetGroup
      createCalibrationUI(modelMesh)
    },
    (progress) => {
      if (progress.total > 0) {
        const pct = Math.round((progress.loaded / progress.total) * 100)
        console.log(`[GameLoop] GLB loading: ${pct}%`)
        const progressEl = document.getElementById('loading-progress')
        if (progressEl) progressEl.innerText = `Loading Assets... ${pct}%`
      }
    },
    (err) => {
      console.error('[GameLoop] Failed to load GLB:', err)
      const progressEl = document.getElementById('loading-progress')
      if (progressEl) progressEl.innerText = 'Error loading assets.'
    }
  )

  // ── Helpers to apply pose data ──────────────────────────────────
  function applyPose(detail: any) {
    if (detail.position) {
      targetGroup.position.set(
        detail.position.x,
        detail.position.y,
        detail.position.z
      )
    }
    if (detail.rotation) {
      targetGroup.quaternion.set(
        detail.rotation.x,
        detail.rotation.y,
        detail.rotation.z,
        detail.rotation.w
      )
    }
    if (detail.scale != null) {
      targetGroup.scale.set(detail.scale, detail.scale, detail.scale)
    }
  }

  // ── Calibration UI ────────────────────────────────────────────────
  function createCalibrationUI(model: THREE.Object3D) {
    const ui = document.createElement('div')
    ui.style.position = 'fixed'
    ui.style.top = '10px'
    ui.style.right = '10px'
    ui.style.zIndex = '10001'
    ui.style.background = 'rgba(0,0,0,0.8)'
    ui.style.color = 'lime'
    ui.style.padding = '10px'
    ui.style.fontFamily = 'monospace'
    ui.style.fontSize = '12px'
    ui.style.borderRadius = '5px'
    ui.style.pointerEvents = 'auto'
    
    // Initial offsets
    const state = {
      px: 0, py: 0, pz: 0,
      rx: 0, ry: 0, rz: 0,
      s: 1
    }

    const valDisplay = document.createElement('pre')
    valDisplay.style.margin = '5px 0 0 0'

    const updateModel = () => {
      model.position.set(state.px, state.py, state.pz)
      model.rotation.set(
        THREE.MathUtils.degToRad(state.rx),
        THREE.MathUtils.degToRad(state.ry),
        THREE.MathUtils.degToRad(state.rz)
      )
      model.scale.set(state.s, state.s, state.s)
      valDisplay.innerText = JSON.stringify(state, null, 2)
    }

    const addControl = (label: string, key: keyof typeof state, step: number) => {
      const container = document.createElement('div')
      container.style.marginBottom = '5px'
      container.innerText = label + ' '
      
      const btnMinus = document.createElement('button')
      btnMinus.innerText = '-'
      btnMinus.onclick = () => { state[key] = parseFloat((state[key] - step).toFixed(3)); updateModel() }
      
      const btnPlus = document.createElement('button')
      btnPlus.innerText = '+'
      btnPlus.onclick = () => { state[key] = parseFloat((state[key] + step).toFixed(3)); updateModel() }

      container.appendChild(btnMinus)
      container.appendChild(btnPlus)
      ui.appendChild(container)
    }

    addControl('PosX', 'px', 0.05)
    addControl('PosY', 'py', 0.05)
    addControl('PosZ', 'pz', 0.05)
    addControl('RotX', 'rx', 5)
    addControl('RotY', 'ry', 5)
    addControl('RotZ', 'rz', 5)
    addControl('Scale', 's', 0.05)

    ui.appendChild(valDisplay)
    document.body.appendChild(ui)
    updateModel()
  }

  // ── Custom Pipeline Module — Three.js Rendering + Image Tracking ──
  //
  // CRITICAL: 8th Wall image tracking events (reality.imagefound, etc.)
  // are NOT dispatched as DOM events on `window`. They are dispatched
  // INTERNALLY within the pipeline. You must use the `listeners` array
  // in your pipeline module to receive them.
  //
  const threejsPipelineModule = () => {
    return {
      name: 'brickgame-threejs',

      // Called when 8th Wall starts and the GL context is ready
      onStart: ({ canvasWidth, canvasHeight }: any) => {
        console.log('[Pipeline] onStart — canvas:', canvasWidth, 'x', canvasHeight)
        renderer.setSize(canvasWidth, canvasHeight)
        camera.aspect = canvasWidth / canvasHeight
        camera.updateProjectionMatrix()
        
        // Hide splash screen only when camera is truly ready
        const splash = document.getElementById('ar-splash')
        if (splash) splash.style.display = 'none'
      },

      // Called every frame with CPU processing results (camera intrinsics)
      onUpdate: ({ processCpuResult }: any) => {
        // Sync Three.js camera with 8th Wall's camera intrinsics
        if (processCpuResult?.reality) {
          const reality = processCpuResult.reality

          // 8th Wall provides a 16-element column-major projection matrix
          if (reality.intrinsics) {
            camera.projectionMatrix.fromArray(reality.intrinsics)
            camera.projectionMatrixInverse.copy(camera.projectionMatrix).invert()
          }

          // Update camera pose from reality
          if (reality.position) {
            camera.position.set(reality.position.x, reality.position.y, reality.position.z)
          }
          if (reality.rotation) {
            camera.quaternion.set(
              reality.rotation.x,
              reality.rotation.y,
              reality.rotation.z,
              reality.rotation.w
            )
          }
        }
      },

      // Called every frame for rendering
      onRender: () => {
        // Draw the game state to the canvas texture
        screen.drawReduxState()
        // Render Three.js scene on the overlay canvas
        renderer.render(scene, camera)
      },

      // Called when canvas resizes
      onCanvasSizeChange: ({ canvasWidth, canvasHeight }: any) => {
        console.log('[Pipeline] onCanvasSizeChange:', canvasWidth, 'x', canvasHeight)
        renderer.setSize(canvasWidth, canvasHeight)
        // CRITICAL: Do NOT call camera.updateProjectionMatrix() here.
        // The projection matrix is managed by 8th Wall's reality.intrinsics!
      },

      // ── Image Tracking Event Listeners ──────────────────────────
      // These are the ONLY correct way to receive image tracking events
      // from 8th Wall. Do NOT use window.addEventListener().
      listeners: [
        {
          event: 'reality.imagefound',
          process: (event: any) => {
            const detail = event.detail || event
            console.log('[Pipeline] ★ reality.imagefound:', JSON.stringify({
              name: detail.name,
              position: detail.position,
              rotation: detail.rotation,
              scale: detail.scale,
            }))

            if (detail.name === IMAGE_TARGET_NAME) {
              targetGroup.visible = true
              applyPose(detail)
              console.log('[Pipeline] Mesh VISIBLE at', targetGroup.position.toArray())
            }
          },
        },
        {
          event: 'reality.imageupdated',
          process: (event: any) => {
            const detail = event.detail || event
            if (detail.name === IMAGE_TARGET_NAME) {
              applyPose(detail)
            }
          },
        },
        {
          event: 'reality.imagelost',
          process: (event: any) => {
            const detail = event.detail || event
            console.log('[Pipeline] reality.imagelost:', detail.name)
            if (detail.name === IMAGE_TARGET_NAME) {
              targetGroup.visible = false
            }
          },
        },
        {
          event: 'reality.imageloading',
          process: (event: any) => {
            const detail = event.detail || event
            console.log('[Pipeline] reality.imageloading:', JSON.stringify(detail))
          },
        },
        {
          event: 'reality.imagescanning',
          process: (event: any) => {
            const detail = event.detail || event
            console.log('[Pipeline] reality.imagescanning:',
              JSON.stringify(detail?.imageTargets?.map((t: any) => t.name)))
          },
        },
      ],
    }
  }

  // ── 8th Wall Session Setup ──────────────────────────────────────

  const startXR = async () => {
    // 1. Fetch the CLI-generated image target JSON
    let imageTargetJson
    try {
      const resp = await fetch('./image-targets/mural.json')
      if (!resp.ok) throw new Error(`HTTP ${resp.status}`)
      imageTargetJson = await resp.json()
      console.log('[GameLoop] Fetched mural.json:', JSON.stringify({
        name: imageTargetJson.name,
        type: imageTargetJson.type,
        imagePath: imageTargetJson.imagePath,
        properties: imageTargetJson.properties,
      }))
    } catch (err) {
      console.error('[GameLoop] Failed to fetch mural.json:', err)
      return
    }

    // 2. Build the image target data for the engine
    const imageTargetData = {
      ...imageTargetJson,
      imagePath: imageTargetJson.imagePath,
      moveable: false,
      physicalWidthInMeters: 0.21,
    }

    console.log('[GameLoop] Configuring imageTargetData:',
      JSON.stringify({ name: imageTargetData.name, imagePath: imageTargetData.imagePath, type: imageTargetData.type }))

    // 3. Configure image targets BEFORE adding pipeline modules
    XR8.XrController.configure({
      imageTargetData: [imageTargetData],
    })
    console.log('[GameLoop] XR8.XrController.configure() called')

    // 4. Register pipeline modules in the correct order
    //    GlTextureRenderer MUST be first (draws camera feed to #camerafeed canvas)
    //    XrController MUST come before our custom module (populates processCpuResult)
    //    Our custom module comes last (reads processCpuResult + renders Three.js to overlay)
    const pipelineModules: any[] = [
      XR8.GlTextureRenderer.pipelineModule(),
      XR8.XrController.pipelineModule(),
      threejsPipelineModule(),
    ]

    // Add XRExtras modules if available (do NOT add Loading, it hides our splash prematurely)
    if (XRExtras?.FullWindowCanvas?.pipelineModule) {
      pipelineModules.push(XRExtras.FullWindowCanvas.pipelineModule())
    }
    if (XRExtras?.RuntimeError?.pipelineModule) {
      pipelineModules.push(XRExtras.RuntimeError.pipelineModule())
    }

    XR8.addCameraPipelineModules(pipelineModules)
    console.log('[GameLoop] Pipeline modules registered:',
      pipelineModules.map((m: any) => m.name || 'unnamed'))

    // 5. Start the XR8 session
    const feedCanvas = document.getElementById('camerafeed') as HTMLCanvasElement
    console.log('[GameLoop] Calling XR8.run() with canvas:', feedCanvas?.id)
    XR8.run({
      canvas: feedCanvas,
      allowedDevices: XR8.XrConfig.device().ANY,
    })

    console.log('[GameLoop] XR8 session started')
  }

  // ── Splash Screen → Start Session ───────────────────────────────
  const splash = document.getElementById('ar-splash')

  const handleStart = () => {
    console.log('[GameLoop] User tapped splash — starting XR')
    const status = document.getElementById('splash-status')
    if (status) status.innerText = 'Initializing AR Camera... Please Wait'
    
    // Disable multiple taps
    if (splash) {
      splash.removeEventListener('click', handleStart)
      splash.removeEventListener('touchstart', handleStart)
    }
    startXR()
  }

  if (splash) {
    splash.addEventListener('click', handleStart)
    splash.addEventListener('touchstart', handleStart)
  } else {
    startXR()
  }

  // ── Window Resize ───────────────────────────────────────────────
  window.addEventListener('resize', () => {
    // CRITICAL: Do NOT update camera aspect/projection matrix here.
    // 8th Wall's pipeline module handles camera intrinsics on resize.
    renderer.setSize(window.innerWidth, window.innerHeight)
  })
}
